server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com  #自定义服务名称的信息
    prefer-ip-address: true #访问路径可以显示IP地址
info:
  app.name: ailsa-microservicecloud
  company.name: www.ailsa.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**  #mydept下的任意路径访问
  ignored-services: "*" #代表的是旧的路径将不能再使用,*代表的是全部
  prefix: /zk